export const NAV = [
  { id: 'tictactoe', title: '01. Tic-Tac-Toe', sub: [] },
  { id: 'virtual-dom', title: '02. Virtual DOM', sub: [] },
  { id: 'function', title: '03. Function', sub: [] },
  { id: 'class', title: '04. Class', sub: [] },
  { id: 'components', title: '05. Components', sub: [] },
  { id: 'closure', title: '06. Closure', sub: [] },
  { id: 'event-loop', title: '07. Event Loop', sub: [] },
  { id: 'event-handling', title: '08. Event Handling', sub: [] },
  { id: 'life-cycle', title: '09. Life Cycle', sub: [] },
  { id: 'ref', title: '10. Ref: DOM', sub: [] },
  { id: 'react-rendering', title: '11. React Rendering', sub: [] },
  { id: 'memoization', title: '12. Memoization', sub: [] },
  {
    id: 'react-hooks',
    title: '13. React Hooks',
    sub: ['use-state', 'use-effect', 'use-memo', 'use-callback', 'use-ref'],
  },
  { id: 'state-management', title: '14. State Management', sub: [] },
]
