export const NAV = [
  { id: 'tictactoe', title: '01. Tic-Tac-Toe' },
  { id: 'virtual-dom', title: '02. Virtual DOM' },
  { id: 'function', title: '03. Function' },
  { id: 'class', title: '04. Class' },
  { id: 'components', title: '05. Components' },
  { id: 'closure', title: '06. Closure' },
  { id: 'event-loop', title: '07. Event Loop' },
  { id: 'event-handling', title: '08. Event Handling' },
  { id: 'life-cycle', title: '09. Life Cycle' },
  { id: 'ref', title: '10. Ref: DOM' },
  { id: 'react-rendering', title: '11. React Rendering' },
  { id: 'memoization', title: '12. Memoization' },
  { id: 'react-hooks', title: '13. React Hooks' },
  { id: 'state-management', title: '14. State Management' },
]
